---
- hosts: web
  become: yes
  vars:
    container_name: thedivyanshupabia.com  # Set your container name here

  tasks:
    - name: Update yum cache and install Docker
      yum:
        name: docker
        state: present
      register: yum_result

    - name: Ensure Docker is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Log in to GitHub Container Registry
      shell: echo "{{ lookup('env', 'GHCR_TOKEN') }}" | docker login ghcr.io -u {{ lookup('env', 'GHCR_USERNAME') }} --password-stdin

    - name: Pull the latest Docker image
      command: "docker pull ghcr.io/{{ lookup('env', 'GHCR_REPOSITORY_OWNER') }}/{{ lookup('env', 'GHCR_REPOSITORY') }}:latest"

    - name: Stop Nginx service if running
      systemd:
        name: nginx
        state: stopped
      ignore_errors: yes

    - name: Stop and remove old container if exists
      shell: |
        docker ps -q --filter "name={{ container_name }}" | grep -q . && docker stop {{ container_name }} || true
        docker ps -a -q --filter "name={{ container_name }}" | grep -q . && docker rm {{ container_name }} || true
      ignore_errors: yes

    - name: Run the new container
      command: >
        docker run -d -p 80:80 -p 443:443
        --name {{ container_name }}
        ghcr.io/{{ lookup('env', 'GHCR_REPOSITORY_OWNER') }}/{{ lookup('env', 'GHCR_REPOSITORY') }}:latest

    - name: Copy Nginx configuration
      copy:
        src: nginx/default
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart Nginx

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted