---
- hosts: web
  become: yes
  vars:
    container_name: thedivyanshupabia.com  # Set your container name here
    ghcr_username: rekklessss
    ghcr_token: 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
    ghcr_repository_owner: rekklessss
    ghcr_repository: thedivyanshupabia.com

  tasks:
    - name: Update yum cache and install Docker
      yum:
        name: docker
        state: present
      register: yum_result

    - name: Ensure Docker is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Log in to GitHub Container Registry
      shell: echo "{{ ghcr_token }}" | docker login ghcr.io -u {{ ghcr_username }} --password-stdin

    - name: Pull the latest Docker image
      command: "docker pull ghcr.io/{{ ghcr_repository_owner }}/{{ ghcr_repository }}:latest"

    - name: Stop Nginx service if running
      systemd:
        name: nginx
        state: stopped
      ignore_errors: yes

    - name: Stop and remove old container if exists
      shell: |
        docker ps -q --filter "name={{ container_name }}" | grep -q . && docker stop {{ container_name }} || true
        docker ps -a -q --filter "name={{ container_name }}" | grep -q . && docker rm {{ container_name }} || true
      ignore_errors: yes

    - name: Run the new container with mounted SSL files
      command: >
        docker run -d -p 80:80 -p 443:443
        --name {{ container_name }}
        -v /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
        -v /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
        -v /etc/letsencrypt/live/thedivyanshupabia.com/fullchain.pem:/etc/letsencrypt/live/thedivyanshupabia.com/fullchain.pem
        -v /etc/letsencrypt/live/thedivyanshupabia.com/privkey.pem:/etc/letsencrypt/live/thedivyanshupabia.com/privkey.pem
        ghcr.io/{{ ghcr_repository_owner }}/{{ ghcr_repository }}:latest

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted