name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Use the Node.js version required by your project

    - name: Install dependencies
      run: npm install

    - name: Build the website
      run: npm run build

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Create dynamic inventory file
      run: |
        echo "[web]" > inventory
        echo "${{ secrets.EC2_PUBLIC_IP }} ansible_ssh_user=ec2-user ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'" >> inventory

    - name: Copy build files to server
      run: |
        rsync -avz --delete dist/ ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/retro-website/dist/
        ssh ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo rsync -avz /home/ec2-user/retro-website/dist/ /usr/share/nginx/html/retro-website/dist/"

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Run Ansible Playbook
      run: ansible-playbook -i inventory deploy.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: "false"